### ISSUE TITLE
Unable to Install on Mac

### ISSUE THREAD

**Issue by ewja1611** [jgclark/BibleGateway-to-Markdown#10]
All of this is way above my head, or at least at this point. I've attempted to install this on my Mac for use in Obsidian but I'm unable to get the computer to install using the provided commands. It is usually showing 'command not found' or not showing anything at all after pressing return. Any help would be appreciated. Would be helpful to have a YouTube video demonstrating install. Thank you.

**Comment by jgclark** [comment]
Hi,
This is a tool to be run from the command line, and so assumes some familiarity with that (whether on Mac, Windows or Linux). It _could_ be incorporated into a workflow for helper apps like Alfred, or possibly someone could write a plugin for Obsidian that incorporates this more easily. (I'm investigating Obsidian myself at the moment, but don't have time to learn another new system just yet.)
Please have a look for Mac command line tutorials. Once you have a working installation of Ruby and can navigate around the filesystem from the command line I can help you get going with this. But I don't have the time to teach command line from scratch, sorry.
