### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by alephtaph** [jgclark/BibleGateway-to-Markdown#11]
Hi jgclark

Thank you for providing the script. I'm new to ruby and I'm running in to some issues:

I have downloaded the ZIP file and placed the bg2md.rb file in a folder in my directory.
Running the command `chmod 755 np*.rb` I get the result "No such file or directory"

Therfore running the script: `bg2md.rb --version TLV --newline --copyright reference` results also in: "-bash: bg2md.rb: command not found"

Any suggestions on how to procede?

Thank you for your support.

Best Regards,
Marco

Mac OS: 11.6 - olorize, optparse, and clipboard installed and updated

**Comment by jgclark** [comment]
Hi @alephtaph. Sorry there must be a typo in the instructions.
I'm away from Mac at the moment, but try `chmod 755 bg2md.rb` instead.

**Comment by alephtaph** [comment]
Hi @jgclark 
I tried it now on a fresh Ubuntu server with the same result.
I used already `chmod 755 bg2md.rb` and had the same result.
Thank you for digging in to this issue.

**Comment by jgclark** [comment]
>
> Hi @jgclark <https://github.com/jgclark>
> I tried it now on a fresh Ubuntu server with the same result.
> I used already chmod 755 bg2md.rb and had the same result.
> Thank you for digging in to this issue.
>
This sounds like its still a basic installation issue, not to do with the
script itself.
You need to be running the script from the directory its installed it, or
add it Linux PATH in the usual way for your command line shell.
Depending on your ruby install as well you might need to prefix the call
with 'ruby '.
So try `ruby bg2md.rb --version TLV --newline --copyright Jn3` or similar.

**Comment by alephtaph** [comment]
ok, whe I call the script like `ruby bg2md.rb --version TLV --newline --copyright Jn3`
I get the result of John 3

But to when I call it ruby `bg2md.rb --version TLV --newline --copyright` I get the error:
_Error: found no useful lines in HTML data, so stopping._

Please excuse my asking. I'm familiar with the terminal and with Linux, but ruby is new ground for me.

**Comment by jgclark** [comment]
You need to supply an actual passage reference in the last example. (I could do with a better error message!)

**Comment by jgclark** [comment]
Updated help text.
