### ISSUE TITLE
Incomplete parsing from Bible Gateway

### ISSUE THREAD

**Issue by C0mele0n** [jgclark/BibleGateway-to-Markdown#12]
Hello. 
I really appreciate what you have done in making this program. However, I continue to have issues:
I ran "bash bg2obs.sh -v KJV -beai" into the terminal to install the KJV version of the Bible on my Mac several times. Every time I run it, it seems to grab the contents in the first chapter of the book and putting that same chapter contents for every following chapter. Otherwise, I get the "[0;31;49mError: could not parse data from BibleGateway: please check your usage, and if still a problem, please raise an issue on GitHub.[0m" error.
Also, Sometimes ill get to see the scripture content of the first chapter (throughout the book, per book, as stated above), and then it will change to give me the error message... I see that the WEB translation that you included works fine. 

I'm wondering if I'm not installing the 2 files correctly (maybe there's something I'm not understanding seeing I'm new to the terminal), or is there an issue in the program related to the KJV version? What am I missing?

One thing I found: I don't know if I understand this line in the instructions:
"Add the .rb script to your PATH, and then set it as executable (`chmod 755 bg2md.rb`)"
I thought I did it, but I'm still getting only the first chapter of each book per book.
[Gen 2.md](https://github.com/jgclark/BibleGateway-to-Markdown/files/7934510/Gen.2.md)
[Gen 3.md](https://github.com/jgclark/BibleGateway-to-Markdown/files/7934512/Gen.3.md)
[Gen 4.md](https://github.com/jgclark/BibleGateway-to-Markdown/files/7934514/Gen.4.md)

**Comment by jgclark** [comment]
Hi, thanks for reaching out.
I didn't write the bg2obs script, so you'll need to go to its author for help there. But from memory it only really wraps my script, so I thought I better check whether KJV is still getting handled OK. It is. 
That said, my script is definitely not designed to "... install a <version> on my Mac ...". That would be breaking the terms of BibleGateway significantly. It's designed for short look-ups under the terms of BG.

**Comment by C0mele0n** [comment]
Thank you so much for your quick response! I looked more closely at the different steps in the instructions and found where I wasnt doing things exactly right. It worked! All the chapters that I clicked on are now true to the chapter name. And sorry I used the wrong term there. I only plan to use it the same way (as a folder to view within Obsidian). Thanks for the heads up on their terms though.

**Comment by jgclark** [comment]
I'm very pleased it's working for you now.
When you're ready, please close this issue.
