### ISSUE TITLE
Bug: Only returns chapter 1 of each book

### ISSUE THREAD

**Issue by selfire1** [jgclark/BibleGateway-to-Markdown#13]
Hi! I have had a couple of people running into an issue in using the script: [Script Only Downloading the 1st Chapter of Every Book · Issue #15 · selfire1/BibleGateway-to-Obsidian](https://github.com/selfire1/BibleGateway-to-Obsidian/issues/15)

Somehow using `v1.4.3` works however. Would you be willing to look into that?

**Comment by jgclark** [comment]
I made a small change a little while back that I can see might have had an impact, and I will look at fixing that.

**Comment by cjolson** [comment]
@jgclark , is there an update? I can't see v1.4.3 as the temporary fix on GitHub anymore. I only see 1.4.0.

**Comment by jgclark** [comment]
@cjolson cc @selfire1 
I realised I'd not made releases for the last few updates; but as its only a single script file, you can just download and use the bg2md.rb script file.  But I have now made a release for v1.4.4 as well.
