### ISSUE TITLE
help modifying script

### ISSUE THREAD

**Issue by GeneralMidi** [jgclark/BibleGateway-to-Markdown#16]
Hi there, 

Could you help me modify the script so that it produces the footnotes and cross references as only numbers? I would like all footnotes (currently lowercase letters) and cross references (currently uppercase letters) to be one continuous numbered list. So far I have modified the script to produce the desired output at the end of the passage, but not in the passage.

This is ideally what I would like...

Lorem ipsum dolor [^3] sit amet, consectetur adipiscing elit. Maecenas[^1] molestie aliquam laoreet. Morbi imperdiet blandit nunc, ac congue diam tristique at. Donec et elit sed sapien interdum ullamcorper. Pellentesque [^2] in volutpat nibh. Praesent sodales tortor sed ornare feugiat. Sed dapibus ipsum a aliquam [^4] pulvinar. 

[^1] is a footnote
[^2] is a footnote
[^3] is a cross ref
[^4] is a cross ref

I really hope it makes sense. Basically process all footnotes first, and in text give them a number instead of a letter. Then process the cross references starting with the next value after the footnotes and give them numbers instead of lettes e.g. [^AB]

This would be very valuable for me if you could at least point me in the right direction how I might make this happen. 

Thank you
Luke

**Comment by jgclark** [comment]
Hi,

It's possible but not entirely straightforward.
From the script, lines 300 and 307 pull out the footnotes and crossrefs respectively into arrays.
Lines 383-394 simplifies the HTML formatting for footnotes and crossrefs, but (importantly) keeps the same letters.  I.e. in `passage.gsub!(%r{<sup>\[<a href.*?>(.*?)</a>\]</sup>}, '[^\1]')` the second parameter means insert markdown footnote syntax around the first (only) match group. You'll need to first extract the match group (e.g. 'D') and then turn that into a number, while keeping track of the total number of footnotes, to add that always to the number of the crossref.
At least lines 427-435 can then be removed and the `hc` and `hf` references replaced with the same numbers as above.

I hope that gives some helpful pointers.
