### ISSUE TITLE
SSL connection refused

### ISSUE THREAD

**Issue by higgsboz-beam** [jgclark/BibleGateway-to-Markdown#20]
I have all of the gems installed and am trying to run this simple script, but keep running into this error. Is there anything that I'm supposed to set up to bypass this?

### Script
```bash
ruby bg2md.rb -b -c -e -r -v NIV Jn 3.16-17 > passage.md
```

### Error
```bash
/Users/<me>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:46:in `connect_nonblock':

  SSL_connect returned=1 errno=0 peeraddr=13.224.214.78:443 state=error:
  certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
```

### System Info
- OS: Ventura 13.4.1
- Ruby: 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
- OpenSSL: 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)

**Comment by jgclark** [comment]
I'm not familiar with .rbenv files, so I don't know what might be going wrong. But it looks to be in your ruby setup.
