### ISSUE TITLE
Getting error when executing

### ISSUE THREAD

**Issue by silbert3** [jgclark/BibleGateway-to-Markdown#21]
Hi and my apologies, I am new and not experienced. Trying to execute and convert a bible to .md - getting the following error:

ruby bg2md.rb -b -c -e -r -v SCH2000 > SCH2000.md
bg2md.rb:7: syntax error, unexpected '<'
<!DOCTYPE html>
bg2md.rb:8: syntax error, unexpected '<'
<html lang="en" data-color-mod...
bg2md.rb:8: syntax error, unexpected local variable or method, expecting end-of-input
<html lang="en" data-color-mode="auto" data-light...
 
Working on Linux Mint, have installed Ruby and Gems as advised. Added to PATH and made script executable
Can anybody help me what I am missing or doing wrong? In general I'd like to have the SCH2000 Bible text in .md to import into Obsidian.

Thanks a lot!
Pat

**Comment by jgclark** [comment]
Given that lines 7 and 8 of the code are just comments, it looks like there's a problem in your configuration. Are other ruby codes working OK? 
Sorry that I cannot provide support for installing ruby, as you're on a platform I don't use.

**Comment by silbert3** [comment]
All I can say is Ruby has been pre-installed with Linux Mint, no tweaks all as it came out of the box - all I did was adding the gems. I am not a programmer and not familiar with Ruby. Apologies. I'll keep trying, but it keeps telling me the same. Also when I strip it of all arguments etc.

**Comment by jgclark** [comment]
>
> All I can say is Ruby has been pre-installed with Linux Mint, no tweaks
> all as it came out of the box - all I did was adding the gems. I am not a
> programmer and not familiar with Ruby. Apologies. I'll keep trying, but it
> keeps telling me the same. Also when I strip it of all arguments etc.
>
In which case I suspect what's happening is that you've not downloaded the
script correctly from GitHub. That might explain the error on "<", at the
start of an HTML tag. Try comparing the script to what you see on GitHub
when you select "Raw" view of the ruby file.
