### ISSUE TITLE
Error: the data returned from BibleGateway is empty

### ISSUE THREAD

**Issue by CptCa1amari** [jgclark/BibleGateway-to-Markdown#27]
Ruby 3.2.4-1 installed w/ gems
Strawberry perl 5.38.2.2 installed and running bg2md.rb
Error: the data returned from BibleGateway is empty, so stopping. Please check your usage, and if still a problem, please raise an issue on GitHub.

**Comment by jgclark** [comment]
It would obviously be helpful to know what parameters you gave in your command, and is this a change from any previous use of the script? There are hundreds of different versions in BG, each of which can be encoded differently.

**Comment by CptCa1amari** [comment]
The command was bg2md.rb [-v] CSB
I also tried ESV, NIV, and KJV and got the same error.

I used v1.4.5-1.5.0

**Comment by CptCa1amari** [comment]
My apologies, I wasn't using the verse tag after the reference. 

User error.
Closing issue.
