### ISSUE TITLE
Importing the WEB

### ISSUE THREAD

**Issue by selfire1** [jgclark/BibleGateway-to-Markdown#4]
Hey, I've run into problems trying to import the Word English Bible. Cross-references are included and all of Jesus' words are deleted (which makes a rather bland Bible).

Just bringing this to your attention, if you wouldn't want to have a look at it, just close the issue.

Here's John 10 for example (inserting `###### v` doesn't make a difference in other translations, so I would guess it doesn't here as well):
```
###### 1   ###### v2   ###### v3   ###### v4   ###### v5   ###### v6 Jesus spoke this parable to them, but they didn't understand what he was telling them.
###### v7 Jesus therefore said to them again,   ###### v8   ###### v9   ###### v10   ###### v11 <crossref intro="10:11">[Isaiah 40:11]; [Ezekiel 34:11-12],[15],[22]</crossref>   ###### v12   ###### v13   ###### v14   ###### v15   ###### v16 <crossref intro="10:16">[Isaiah 56:8]</crossref>   ###### v17  <crossref intro="10:17">[Isaiah 53:7-8]</crossref>   ###### v18 
###### v19 Therefore a division arose again among the Jews because of these words.  ###### v20 Many of them said, "He has a demon, and is insane! Why do you listen to him?"  ###### v21 Others said, "These are not the sayings of one possessed by a demon. It isn't possible for a demon to open the eyes of the blind, is it?"<crossref intro="10:21">[Exodus 4:11]</crossref>
###### v22 It was the Feast of the Dedication at Jerusalem.  ###### v23 It was winter, and Jesus was walking in the temple, in Solomon's porch.  ###### v24 The Jews therefore came around him and said to him, "How long will you hold us in suspense? If you are the Christ, tell us plainly."
###### v25 Jesus answered them,   ###### v26   ###### v27   ###### v28   ###### v29   ###### v30 
###### v31 Therefore the Jews took up stones again to stone him.  ###### v32 Jesus answered them, 
###### v33 The Jews answered him, "We don't stone you for a good work, but for blasphemy: because you, being a man, make yourself God."
###### v34 Jesus answered them, <crossref intro="10:34">[Psalm 82:6]</crossref>  ###### v35   ###### v36   ###### v37   ###### v38 
###### v39 They sought again to seize him, and he went out of their hand.  ###### v40 He went away again beyond the Jordan into the place where John was baptizing at first, and he stayed there.  ###### v41 Many came to him. They said, "John indeed did no sign, but everything that John said about this man is true."  ###### v42 Many believed in him there.
```

**Comment by jgclark** [comment]
Indeed it would be bland, and pointless!

I've tried this with my unchanged script for World (not Word) English Version and John 10, and it works fine. I suspect that what's happening is related to the bold markers (**...**) that's added in place of red-lining the words of Jesus. I guess your script is getting tripped up by them.

Good news, though. I've added two options, available now in v1.4, that I think you'll really like. Please see the CHANGELOG, turn on the appropriate settings, and simplify your script. Let me know how it goes.

**Comment by selfire1** [comment]
Thanks, I indeed am really excited about the new features. That makes my attempts hacking your script without any idea of ruby redundant. Thanks. I'll also incorporate your recommendation link to (rather than fork) your script to keep it updated. Thanks for being so responsive.

Using the new script (and initially with the previous version) I've run into an issue with the clipboard: 
```
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- clipboard (LoadError)
	from <internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from bg2md.rb:78:in `<main>'
```

Do you have an idea what the issue might be?

**Comment by jgclark** [comment]
That looks a simple one. Even if you don't know Ruby, you can probably see the error arises in line 78, which is a `require 'clipboard'` statement. That means you're missing a gem, which you need to install, along with the others you've already done. Details in the (now fuller) README.
