### ISSUE TITLE
Request: Implement for StudyLight

### ISSUE THREAD

**Issue by Rollerbahn** [jgclark/BibleGateway-to-Markdown#5]
Not so much an issue, but I wanted to reach out to see if this kind of script could be implemented for Studylight.org as well? I think that would be really awesome!

Thanks

**Comment by jgclark** [comment]
Thanks, @Rollerbahn, I'd not been aware of Studylight.org until now. 
I've had a quick look and it certainly seems that exactly the same sort of script could be implemented. This script could be used as a basis for this, and I'd very happy for it to be used in this way.
But unless there's something about it that means I'd switch over to using it, I'm sorry I'm not going to offer to do the work.
