### ISSUE TITLE
Error: found no useful lines in HTML data, so stopping.

### ISSUE THREAD

**Issue by Yionnara** [jgclark/BibleGateway-to-Markdown#7]
![image](https://user-images.githubusercontent.com/33164097/114319534-31abee80-9b12-11eb-830b-e7e45afbdd95.png)
Launching on Debian 9 with Ruby 2.6.0 and Ruby 2.7.0 with all dependencies...
Don't know what should i do :(

**Comment by Yionnara** [comment]
> ![image](https://user-images.githubusercontent.com/33164097/114319534-31abee80-9b12-11eb-830b-e7e45afbdd95.png)
> Launching on Debian 9 with Ruby 2.6.0 and Ruby 2.7.0 with all dependencies...
> Don't know what should i do :(

My bad didn't understand how it works if i need help i contact you later

**Comment by jgclark** [comment]
Read the README and then supply an actual reference to fetch.
