### ISSUE TITLE
new to code (need help)

### ISSUE THREAD

**Issue by cmd-mike** [jgclark/BibleGateway-to-Markdown#8]
I got lost after at bg2md.rb [options] reference.
i downloaded ruby, installed all the gems 
bg2md.rb ran fine 
but i dont know what to do with bg2md.rb
??? 
Thanks

**Comment by cmd-mike** [comment]
nevermind i got it
thank you for your sacrifice in coding this

**Comment by jgclark** [comment]
Glad you got there, @cmd-mike. I hope it helps you in ministry.
